### ISSUE TITLE
Kernel32.dll not found on Linux

### ISSUE THREAD

**Issue by NicolasDorier** [hhblaze/DBreeze#42]
dotnet core 2.0 with 1.88.2 on linux
```
Failed   NBXplorer.Tests.UnitTest1.RepositoryCanTrackAddresses
Error Message:
 DBreeze.Exceptions.DBreezeException : Getting table "@utKeysByScript" from the schema failed!
---- DBreeze.Exceptions.TableNotOperableException : DBreeze.Scheme
-------- DBreeze.Exceptions.DBreezeException : Rollback of the table "DBreeze.Scheme" failed!
------------ DBreeze.Exceptions.DBreezeException : Restore rollback file "RepositoryCanTrackAddresses/_DBreezeSchema" failed!
---------------- System.DllNotFoundException : Unable to load DLL 'kernel32.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at DBreeze.Transactions.TransactionsCoordinator.GetTable_WRITE(String tableName, Int32 transactionThreadId)
   at DBreeze.Transactions.Transaction.GetWriteTableFromBuffer(String tableName)
   at DBreeze.Transactions.Transaction.Insert[TKey,TValue](String tableName, TKey key, TValue value, Byte[]& refToInsertedValue, Boolean& WasUpdated, Boolean dontUpdateIfExists)
   at DBreeze.Transactions.Transaction.Insert[TKey,TValue](String tableName, TKey key, TValue value)
   at NBXplorer.Repository.InsertKeyInformation(Transaction tx, Script scriptPubKey, KeyInformation info) in /mnt/e/Sources/NBXplorer/NBXplorer/temp/NBXplorer/NBXplorer/Repository.cs:line 347
   at NBXplorer.Repository.MarkAsUsed(KeyInformation info) in /mnt/e/Sources/NBXplorer/NBXplorer/temp/NBXplorer/NBXplorer/Repository.cs:line 262
   at NBXplorer.Tests.UnitTest1.RepositoryCanTrackAddresses(RepositoryTester tester) in /mnt/e/Sources/NBXplorer/NBXplorer/temp/NBXplorer/NBXplorer.Tests/UnitTest1.cs:line 51
   at NBXplorer.Tests.UnitTest1.RepositoryCanTrackAddresses() in /mnt/e/Sources/NBXplorer/NBXplorer/temp/NBXplorer/NBXplorer.Tests/UnitTest1.cs:line 31
----- Inner Stack Trace -----
   at DBreeze.Scheme.GetTable(String userTableName)
----- Inner Stack Trace -----
   at DBreeze.LianaTrie.LTrieRootNode.RollBack()
   at DBreeze.LianaTrie.LTrie.RollBack()
----- Inner Stack Trace -----
   at DBreeze.LianaTrie.LTrieWriteCache.RollBack()
   at DBreeze.LianaTrie.LTrieRootNode.RollBack()
----- Inner Stack Trace -----
   at DBreeze.Storage.FSR.FlushFileBuffers(IntPtr hFile)
   at DBreeze.Storage.FSR.NET_Flush(FileStream mfs)
   at DBreeze.Storage.FSR.Rollback()
```

**Comment by Behrooz-Amoozad** [comment]
What does System.Environment.OSVersion say about the operating system?
You should use a debug version of DBreeze so that you can have line numbers in your stack track.

**Comment by NicolasDorier** [comment]
Unix 4.4.0.43

**Comment by Behrooz-Amoozad** [comment]
Um, are you using DBreeze.UWP?

**Comment by NicolasDorier** [comment]
No, .netcore2.0 on ubunutu (WSL)

**Comment by NicolasDorier** [comment]
1.87.0 do not have this issue.

**Comment by Behrooz-Amoozad** [comment]
oh, I was looking at the wrong code(compiler switches got me confused for a moment, sorry)
breakpoint at DBreeze/Storage/FSR.cs NET_FLUSH  and FlushFileBuffers() and see if it's where the exception raises.

**Comment by hhblaze** [comment]
Guys, I am away right now. Will fix that on the next Tuesday...

**Comment by hhblaze** [comment]
v1.089
