### ISSUE TITLE
Getting "Getting table "@utCoins" from the schema failed!" when calling Technical_SetTable_OverwriteIsNotAllowed

### ISSUE THREAD

**Issue by fenix2222** [hhblaze/DBreeze#57]
We are getting intermittent exception 
```
DBreeze.Exceptions.DBreezeException: Getting table "@utCoins" from the schema failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: /Deployment/NodeData/cirrus/CirrusMain/coinview/10000002 ---> System.IO.IOException: Device or resource busy
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at DBreeze.Storage.FSR.InitFiles()
   --- End of inner exception stack trace ---
   at DBreeze.Scheme.GetTable(String userTableName)
   --- End of inner exception stack trace ---
   at DBreeze.Transactions.TransactionsCoordinator.GetTable_WRITE(String tableName, Int32 transactionThreadId)
   at DBreeze.Transactions.Transaction.GetWriteTableFromBuffer(String tableName)
   at DBreeze.Transactions.Transaction.Technical_SetTable_OverwriteIsNotAllowed(String tableName)
```
https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs#L198

I think it is related to https://github.com/hhblaze/DBreeze/issues/15. We are using `transaction.SynchronizeTables("BlockHash", "Coins", "Rewind");` and database is not corrupt.

**Comment by hhblaze** [comment]
Please reproduce that on a clean Db then return back, your file can be corrupted.

**Comment by hhblaze** [comment]
Ah, no... it is mentioned in the exception:
"coinview/10000002 ---> System.IO.IOException: Device or resource busy"
External program (or the same) try to read the file and it is blocked by OS for IO.
